### ISSUE TITLE
Configration parameters

### ISSUE THREAD

**Issue by ArieHein** [jdhitsolutions/MemoryTools#5]
Put the configuration parameters as to what is considered a warning or critical outside of the script, maybe a .json file.

Allow the usage of percentage (optional: based on the size of the drive), not necesarilty a set number like 500MB.

**Comment by jdhitsolutions** [comment]
I understand your reasoning. I dislike having a user-maintained file because they'd have to navigate to the module folder to find and edit it. What I could do is set those via parameters with default value. That way, you could use $PSDefaultParameterValues in your profile if you really wanted something different.

**Comment by jdhitsolutions** [comment]
It would also make sense to use the same settings for Show-MemoryUsage so I'll have to think about this.

**Comment by jdhitsolutions** [comment]
Pushed a change (v0.2.6) where there is now a settings script file that can be modified. You can change the variables in the file for persistent changes, or because the variables are global, you could make temporary changes per session.  I'll leave this issue open for a bit hoping for some feedback on this approach.
